In [1]:
import numpy as np

PQ: eigen-things

In [26]:
# 2
ev2 = np.linalg.eig(np.array([[1,0],[0,2]]))
ev2

(array([1., 2.]),
 array([[1., 0.],
        [0., 1.]]))

In [31]:
# 4
ev4 = np.linalg.eig(np.array([[3,4],[0,5]]))
ev4

(array([3., 5.]),
 array([[1.        , 0.89442719],
        [0.        , 0.4472136 ]]))

In [32]:
# 6
ev6 = np.linalg.eig(np.array([[1,0],[-1,4]]))
ev6

(array([4., 1.]),
 array([[0.        , 0.9486833 ],
        [1.        , 0.31622777]]))

In [33]:
# 8
ev8 = np.linalg.eig(np.array([[-3,8],[2,3]]))
ev8

(array([-5.,  5.]),
 array([[-0.9701425 , -0.70710678],
        [ 0.24253563, -0.70710678]]))

In [35]:
# 9
ev9 = np.linalg.eig(np.array([[5,4],[-4,-3]]))
ev9

(array([1.+2.98023224e-08j, 1.-2.98023224e-08j]),
 array([[ 0.70710678+0.00000000e+00j,  0.70710678-0.00000000e+00j],
        [-0.70710678+5.26835606e-09j, -0.70710678-5.26835606e-09j]]))

In [36]:
# 10
ev10 = np.linalg.eig(np.array([[-2,-3],[1,1]]))
ev10

(array([-0.5+0.8660254j, -0.5-0.8660254j]),
 array([[ 0.8660254+0.j  ,  0.8660254-0.j  ],
        [-0.4330127-0.25j, -0.4330127+0.25j]]))

<hr style="border:1px solid gray"> </hr>

PQ: Diagonalization and Applications

In [52]:
# 1
T = np.array([[6,-1],[2,3]])
C = np.linalg.eig(T)[1]
invC = np.linalg.inv(C)
D = invC @ T @ C
T, C, invC, D

(array([[ 6, -1],
        [ 2,  3]]),
 array([[0.70710678, 0.4472136 ],
        [0.70710678, 0.89442719]]),
 array([[ 2.82842712, -1.41421356],
        [-2.23606798,  2.23606798]]),
 array([[5.0000000e+00, 8.8817842e-16],
        [0.0000000e+00, 4.0000000e+00]]))

In [53]:
# 2
T = np.array([[2,7],[0,-1]])
C = np.linalg.eig(T)[1]
invC = np.linalg.inv(C)
D = invC @ T @ C
T, C, invC, D

(array([[ 2,  7],
        [ 0, -1]]),
 array([[ 1.        , -0.91914503],
        [ 0.        ,  0.3939193 ]]),
 array([[1.        , 2.33333333],
        [0.        , 2.53859104]]),
 array([[ 2.0000000e+00, -4.4408921e-16],
        [ 0.0000000e+00, -1.0000000e+00]]))

In [55]:
# 3
T = np.array([[1,0],[2,-1]])
C = np.linalg.eig(T)[1]
invC = np.linalg.inv(C)
D = invC @ T @ C
T, C, invC, D

(array([[ 1,  0],
        [ 2, -1]]),
 array([[0.        , 0.70710678],
        [1.        , 0.70710678]]),
 array([[-1.        ,  1.        ],
        [ 1.41421356,  0.        ]]),
 array([[-1.,  0.],
        [ 0.,  1.]]))

In [57]:
# 4
C = np.array([[1,2],[0,1]])
invC = np.linalg.inv(C)
D = np.identity(2)
T = C @ D @ invC
T, C, invC, D

(array([[1., 0.],
        [0., 1.]]),
 array([[1, 2],
        [0, 1]]),
 array([[ 1., -2.],
        [ 0.,  1.]]),
 array([[1., 0.],
        [0., 1.]]))

In [59]:
# 5
C = np.array([[1,1],[1,2]])
invC = np.linalg.inv(C)
D = np.array([[5,0],[0,4]])
T = C @ D @ invC
T, C, invC, D

(array([[ 6., -1.],
        [ 2.,  3.]]),
 array([[1, 1],
        [1, 2]]),
 array([[ 2., -1.],
        [-1.,  1.]]),
 array([[5, 0],
        [0, 4]]))

In [64]:
T3 = C @ D ** 3 @ invC
T3, T ** 3, T @ T @ T

(array([[186., -61.],
        [122.,   3.]]),
 array([[216.,  -1.],
        [  8.,  27.]]),
 array([[186., -61.],
        [122.,   3.]]))

In [65]:
# 6
C = np.array([[7,1],[-3,0]])
invC = np.linalg.inv(C)
D = np.array([[-1,0],[0,2]])
T = C @ D @ invC
T, C, invC, D, T @ T @ T

(array([[ 2.,  7.],
        [ 0., -1.]]),
 array([[ 7,  1],
        [-3,  0]]),
 array([[ 0.        , -0.33333333],
        [ 1.        ,  2.33333333]]),
 array([[-1,  0],
        [ 0,  2]]),
 array([[ 8., 21.],
        [ 0., -1.]]))

In [66]:
# 7
C = np.array([[1,0],[1,1]])
invC = np.linalg.inv(C)
D = np.array([[1,0],[0,-1]])
T = C @ D @ invC
T, C, invC, D, T @ T @ T @ T @ T

(array([[ 1.,  0.],
        [ 2., -1.]]),
 array([[1, 0],
        [1, 1]]),
 array([[ 1.,  0.],
        [-1.,  1.]]),
 array([[ 1,  0],
        [ 0, -1]]),
 array([[ 1.,  0.],
        [ 2., -1.]]))